local mapping = require("utils.commons").mapping

mapping("bufferline")
mapping("general")
mapping("neotree")
mapping("harpoon")
mapping("telescope")
mapping("trouble")
mapping("spectre")
mapping("lspsaga")
mapping("close_others")
mapping("smart-splits")
mapping("noice")
mapping("jester")
mapping("neotest")
