require('user.mappings.general')
require('user.mappings.lspsaga')
require('user.mappings.far')
require('user.mappings.movement')
require('user.mappings.neotree')
require('user.mappings.telescope')
require('user.mappings.bufferline')
require('user.mappings.trouble')
-- require('user.mappings.which-key')
