lvim.plugins = {
	require("user.plugins.dracula"),
	require("user.plugins.catppuccin"),
	require("user.plugins.github"),
	require("user.plugins.oxocarbon"),
	require("user.plugins.tokyonight"),
	require("user.plugins.lspsaga"),
	require("user.plugins.colorizer"),
	require("user.plugins.noice"),
	require("user.plugins.discord"),
	require("user.plugins.window"),
	require("user.plugins.neotree"),
	require("user.plugins.lspkind"),
	require("user.plugins.copilot").copilot,
	require("user.plugins.copilot").chat,
	require("user.plugins.minimap"),
	require("user.plugins.numb"),
	require("user.plugins.autotag"),
	require("user.plugins.context"),
	require("user.plugins.neoscroll"),
	require("user.plugins.todo"),
	require("user.plugins.surround"),
	require("user.plugins.ufo"),
	require("user.plugins.flash"),
	require("user.plugins.visual-multi"),
	require("user.plugins.trouble"),
	require("user.plugins.inlayhints"),
	require("user.plugins.tailwind-colors"),
	require("user.plugins.tailwind-cmp"),
	require("user.plugins.tailwindcss-fold"),
	require("user.plugins.diffview"),
	require("user.plugins.markview"),
	-- require("user.plugins.better-escape"),
	require("user.plugins.mini-icons"),
	require("user.plugins.image-preview"),
	-- require("user.plugins.outline"),
	require("user.plugins.edgy"),
	require("user.plugins.spectre"),
	require("user.plugins.nui-components"),
	-- require("user.plugins.dressing"),
	require("user.plugins.harpoon"),
	require("user.plugins.lsp-endhints"),
	require("user.plugins.mini-surround"),
	require("user.plugins.mini-git"),
	require("user.plugins.legendary"),
	require("user.plugins.conform"),
	-- require("user.plugins.git-blame"),
	require("user.plugins.tiny-inline-diagnostic"),
	require("user.plugins.gitsigns-nvim"),
	require("user.plugins.startuptime"),
	require("user.plugins.profile"),
	require("user.plugins.smart-splits"),
	require("user.plugins.dap-vscode-js"),
	require("user.plugins.dap-go"),
}
