lvim.plugins = {
  require('user.plugins.lspsaga'),
  require('user.plugins.colorizer'),
  require('user.plugins.noice'),
  require('user.plugins.discord'),
  require('user.plugins.window'),
  require('user.plugins.neotree'),
  require('user.plugins.dracula'),
  require('user.plugins.lspkind'),
  require('user.plugins.copilot').copilot,
  require('user.plugins.copilot').chat,
  require('user.plugins.minimap'),
  require('user.plugins.numb'),
  require('user.plugins.autotag'),
  require('user.plugins.context'),
  require('user.plugins.neoscroll'),
  require('user.plugins.todo'),
  require('user.plugins.surround'),
  require('user.plugins.ufo'),
  require('user.plugins.flash'),
  require('user.plugins.visual-multi'),
  require('user.plugins.trouble'),
  require('user.plugins.inlayhints'),

}
